### ISSUE TITLE
function C2rpy in compare_estimate_to_ground_truth is missing!

### ISSUE THREAD

**Issue by MinaHenein** [robotic-esp/dataset_tools#1]

**Comment by kjudd1** [comment]
Hi, thanks for bringing this up. This was an issue in the past but should have been fixed with commit bf52f27. Are you still having issues with the most recent version?

**Comment by MinaHenein** [comment]
Great, thanks a lot. 
In the same function, what exactly is the meaning of the boolean variable body_frame?
