### ISSUE TITLE
What is the depth scale?

### ISSUE THREAD

**Issue by javrtg** [robotic-esp/dataset_tools#2]
Amazing work :)
I just have a question regarding the Realsense D435: What depth scale is being used in the dataset?
I couldn't find it neither in the paper nor in the website,
Thanks in advance!

**Comment by kjudd1** [comment]
Hi Javier, the depth_scale value in the Realsense driver was not changed from the default of 0.001, which means the values in the depth image correspond directly to milimeters. Is that what you are looking for?

**Comment by javrtg** [comment]
Hi @kjudd1, thanks a lot! That is what I was looking for :)
