### ISSUE TITLE
Trajectory alignment to the ground-truth

### ISSUE THREAD

**Issue by javrtg** [robotic-esp/dataset_tools#3]
Thanks a lot for open-sourcing this great work :)

I've got a question regarding the alignment of the estimated trajectory of the objects with the ground-truth of the vicon: What is the proper way of doing it?

After reading the [The Oxford Multimotion Dataset paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8610209&casa_token=wt0urKR6Nn4AAAAA:YA0doviOs0L3I6Yh4oHbHGkL6NHm0s1Nu3K1ixtpnjewAeQ9RVCgWYv8qsjY70tUnlBa3CfqpA&tag=1) and the [MVO paper](https://www.robots.ox.ac.uk/~mobile/Papers/2018IROS_judd.pdf) and having a look at the code, I am not sure if I understood it correctly. Concretely, if I have an estimated trajectory of an object, if I want to align it to the ground-truth trajectory, I think that I have to perform two rigid transformations. For example, in the following situation:

![image](https://user-images.githubusercontent.com/71815905/134195250-8dab6458-632b-44a0-aa34-4fbb7642c5ce.png)

Where we have two different poses for an object at frames (i) and (i+1), the estimated poses are RGB colored with solid lines in the front face of the object and are expressed with respect to an estimated world reference represented in black and with solid lines, and finally the groun-truth data are represented with the same conventions as before but with dashed lines.

Given the arbitrariness of the initial pose of the objects, as noted in the paper, I believe the following transformations (in bold) are needed to align the estimated trajectory with the ground-truth trajectory:

![image](https://user-images.githubusercontent.com/71815905/134198227-76efa0f9-552c-43c9-a1e1-c81892943519.png)

Is this wrong? I am doubting because in the paper there is only a mention to one of the transformations.

Besides, what are your recomendations/ guidelines to perform the alignment? I feel this kind of alignment is different than with visual odometry because of the mentioned arbitrariness of the initial pose of the objects.

Thanks in advance!

**Comment by kjudd1** [comment]
Hi @JavierTG97 thanks for your interest.

Part of your ambiguity can be resolved by using the camera frame as your estimated world origin. For example, If you are using the stereo data, you can assign _w1_ to the left camera and use the camera-to-apparatus transform (_T_AL_ in the [OMD paper](https://arxiv.org/pdf/1901.01445.pdf), _w2_T_w1_ in your notation) provided in the  kalibr.yaml calibration file. This anchors your estimation frame to the ground truth frame in a known way.

The rest of the ambiguity comes from _o2_T_o1_ which can be found via a calibration holdout of the first few frames of each trajectory (this is the method described in the MVO papers, [here](https://arxiv.org/pdf/1808.00274.pdf) and [here](https://arxiv.org/pdf/1808.00274.pdf). The `find_alignment_T_A_from_B.m` script shows how this can be done and is similar to how standard VO/egomotion trajectories can be calibrated.

Hopefully that clarifies things but let me know if you have any more questions!

**Comment by javrtg** [comment]
Thanks a lot @kjudd1 :) This answer has been  really helpful,
Just for the sake of understanding the second step:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; estimated(w2_T_o1) * o1_T_o2 = estimated(w2_T_o2) )

is it performed by iteratively minimizing the error in the lie algebra space:?

![image](https://user-images.githubusercontent.com/71815905/134246091-a6d312f3-9af7-4350-a3d2-97dc4517a08f.png)
(I am sorry that I  believe I am using here different notation conventions than the ones used in the papers: Having a transform A_T_B, this allows the transformation of points, p, expressed in frame B to frame A by: p_A = A_T_B * p_B)

Following this, and using the script from the repository, Would be this the proper way of getting o1_T_o2? : 
```o2_T_o1 = find_alignment_T_A_from_B(o1_T_w2, o2_T_w2)```

Again, thanks a lot for your time

**Comment by kjudd1** [comment]
Yes the minimization is done in the lie algebra space. But the error transform is slightly more complex because it expresses the estimated trajectory in the ground-truth frame for direct comparison:
![image](https://user-images.githubusercontent.com/17728335/134720345-745f4798-ea3a-4483-b03e-cc543019c987.png).
Here `o_i` and `o_{i+1}` are the estimated object frames and `o_i^{GT}` and `o_{i+1}^{GT}` are their ground-truth counterparts (`o1` and `o2` at times `i` and `i+1` in your image above). The `F` transforms are body deformations matrices that are identity for rigid motion. So,
`o1_T_o2 = T_{o_i o_i^{GT}} = argmin_(T_{o_i o_i^{GT}}) (T_err)`.

The script actually takes two sequences of transforms and attempts to align them so it would be more like:
`o1_T_o2 = find_alignment_T_A_from_B({o1^(i+1)_T_o1^(i)}_i=0..k-1, {o2^(i+1)_T_o2^(i)}_i=0..k-1)`,
where
`{o1^(i+1)_T_o1^(i)}_i=0..k-1`
is the sequence of transforms from frame `o1` at time `i` and to frame `o1` at time `i+1` for `k` time steps (i.e., the estimated object motion). It basically aligned the sequences of estimated and ground-truth transforms for each motion in the same way you would for an egomotion estimate. Make sure you're careful with the order of the parameters as you may end up with the inverse of what you're looking for.

The notation for this gets complex quickly. I've tried to translate between our notations but let me know if any of that needs more explanation.

**Comment by javrtg** [comment]
Oh I see! thanks a lot @kjudd1, your answers have been of tremendous help. 
I'm just beggining to work at odometry projects so I think this is why I haven't had come across with the proper way of doing the alignment before. 

Just if it's not improper to ask it, is there a reason why the alignment should be done by using the relative motions instead of using the absolute poses (like with the equation I wrote in my second comment)?

Thanks again and sorry for the many questions.

**Comment by kjudd1** [comment]
No worries @JavierTG97  I hope this dataset is useful to you.

There are a lot of different ways to evaluate estimation accuracy and they differ in very nuanced ways. This method is based on visual odometry, evaluating the absolute trajectory accuracy relative to the object's initial pose in the object's own frame. You could instead evaluated the accuracy of the object's estimated position in some other frame, like the original camera frame or even the moving camera frame over time. This would be a more SLAM-minded approach. Neither one is necessarily better than the other and they're tightly coupled (you can move between them with a bit of transform math), but they just evaluate slightly different things.

Just make sure you're very careful about what frame you are evaluating your errors in. If you are evaluating third-party object trajectories in some other frame (e.g., the camera/world frame), dealing with the ambiguities between the estimated and ground-truth object frames for each of the multiple objects gets complicated quickly and the tools here might not be designed for that.

**Comment by javrtg** [comment]
I think I understand it a lot better now, thanks a lot (once again :)),
Concretely, in the project I'm working on, all the object poses are w.r.t. the same reference frame (the initial pose of the camera), so I think I will follow the SLAM-minded approach,

This dataset is being of great help to test the project, and reading your related papers have been really worthy as well,
gracias!! (spanish user here :))
Best wishes.
