### ISSUE TITLE
Wrong depth value from rgbd.tgz

### ISSUE THREAD

**Issue by zj2013** [robotic-esp/dataset_tools#4]
First of all, thank you for your public multi-motion dataset, which is very helpful to my research.
However, when I use  the following code to combine the rgb and depth image in **rgbd.tgz** to generate point clouds, there are wrong results. 
```
void GeneratePointCloud(cv::Mat &rgb, cv::Mat &depth, pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud)
{
    double fx = 618.3587036132812, fy = 618.5924072265625, cx = 328.9866333007812, cy = 237.7507629394531;
    for ( int m=0; m<(depth.rows); m+=1 )
    {
        for ( int n=0; n<(depth.cols); n+=1 )
        {
            {
                float d = depth.ptr<float>(m)[n];///1000.0;

                if (d < 0.01 || d>100)
                    continue;
                pcl::PointXYZRGBA p;

                p.z = d;
                p.x = ( n - cx ) * p.z / fx;
                p.y = ( m - cy ) * p.z / fy;

                if(rgb.type() == 24)   //CV_8UC4
                {
                    p.b = rgb.ptr<uchar>(m)[n*4];
                    p.g = rgb.ptr<uchar>(m)[n*4+1];
                    p.r = rgb.ptr<uchar>(m)[n*4+2];
                    p.a = rgb.ptr<uchar>(m)[n*4+3];
                }
                else if(rgb.type() == 16)   //CV_8UC3
                {
                    p.b = rgb.ptr<uchar>(m)[n*3];
                    p.g = rgb.ptr<uchar>(m)[n*3+1];
                    p.r = rgb.ptr<uchar>(m)[n*3+2];
                }

                cloud->points.push_back( p );
            }
        }
    }
    return;
}
void main()
{
        cv::Mat imRGB = cv::imread(base_folder + "/"  + "000000_color.png", CV_LOAD_IMAGE_UNCHANGED);
        cv::Mat imD = cv::imread(base_folder + "/" +  "000000_aligned_depth.png", CV_LOAD_IMAGE_UNCHANGED);
        imD.convertTo(imDf, CV_32F, 0.001);
        pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud_raw (new pcl::PointCloud<pcl::PointXYZRGBA>);
        GeneratePointCloud(imRGB, imD, cloud_raw);

        string save_ply_path = base_folder + "/pointcloud/" + "0.ply";
        pcl::io::savePLYFile(save_ply_path, *cloud_raw);
}
```

The wavy effect appears in the originally flat point cloud.  I have tested swinging_4_unconstrained, calibration_extrinsic and other sequences, and the results are all like this. The details are shown in the following figure(
**Front and side views** of the first frame of the point cloud in the **calibration_extrinsic** sequence). 
**Is there something wrong with the code or the depth image itself ?**
![front-view](https://user-images.githubusercontent.com/37093136/180913454-48bcc56a-fd9b-4073-8b02-b7adb6af4b7e.png)
![side-view](https://user-images.githubusercontent.com/37093136/180910604-92318cbc-a04b-4a66-9619-db7f99bcef93.png)

**Comment by gammell** [comment]
Hello @zj2013,
Thanks for opening this issue. You state that:

> The wavy effect appears in the originally flat point cloud. 

Can you explain what you mean when you say the point cloud is "originally" flat? Is it flat before you are plotting it or just that you expect it to be flat?

Thanks

**Comment by zj2013** [comment]
Thank you for your reply.
The scene from the **calibration_extrinsic sequence** contains a large number of planes, including floors, walls, and calibration board. So the generated point cloud should contain many corresponding planes. However, it is not.  In particular, the point cloud corresponding to the checkerboard calibration board is not a plane. This can be seen in the side view (the second image) of the point cloud.
The pointcloud file can be download from the following [link：](https://rec.ustc.edu.cn/share/bdde6a90-0cdb-11ed-9811-75733efd953d) the corresponding password ：**rg3q**

**Comment by gammell** [comment]
Raw RGB-D data is often quite noisy, so this is likely just the quality of raw depth data from the Intel Realsense D435 in this situation.

Please note that I haven't looked at your code.
